default: Upscaling_with_OCVFEM.tex
	pdflatex -shell-escape Upscaling_with_OCVFEM
	pdflatex -shell-escape Upscaling_with_OCVFEM

clean:
	rm -rf *.aux *.log *.blg *.bbl *.spl *.log *.out *-eps-converted-to.pdf Upscaling_with_OCVFEM.pdf *lof *toc
